name: pd_app
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.10
  - pip=23.1.2
  #- cudatoolkit=11.8
  #- pytorch=2.0.1
  #- torchvision=0.15.2
  - numpy=1.24.3
  - pip:
    #- xformers==0.0.17rc482
    - torch==2.0.0+cu118 torchvision==0.15.1+cu118 --extra-index-url=https://download.pytorch.org/whl/cu118
post_build:
  #- python -m spacy download es_core_news_lg
  #- python -m spacy download en_core_web_lg
  #- pip install torch==2.0.0+cu118 torchvision==0.15.1+cu118 --extra-index-url https://download.pytorch.org/whl/cu118


# [Enhancement] install torch==2.0.0+cu118 torchvision==0.15.1+cu118 xformers==0.0.17rc482
# pip install torch==2.0.0+cu118 torchvision==0.15.1+cu118 --extra-index-url https://download.pytorch.org/whl/cu118