name: pandreamonium_app
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.10
  - pip=23.1.2  # Last pip version
  # - cudatoolkit=11.8
  # - pytorch=2.0.0
  # - torchvision=0.15.1
  - pip:
    - -r requirements.txt
    #- torch==2.0.0+cu118 torchvision==0.15.1+cu118 --extra-index-url https://download.pytorch.org/whl/cu118
commands:
  - conda activate pandreamonium_app
  - pip install torch==2.0.0+cu118 torchvision==0.15.1+cu118 --extra-index-url https://download.pytorch.org/whl/cu118
  - python -m spacy download es_core_news_lg
  - python -m spacy download en_core_web_sm  # KeyphraseVectorizer dependency
  #- python -m spacy download en_core_web_lg

# [Enhancement] install torch==2.0.0+cu118 torchvision==0.15.1+cu118 xformers==0.0.17rc482
# pip install torch==2.0.0+cu118 torchvision==0.15.1+cu118 --extra-index-url https://download.pytorch.org/whl/cu118